99 Cats/cats_app/config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "cats#index"

  resources :cats, except:[:destroy]


end

99 Cats/cats_app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

99 Cats/cats_app/app/models/cat.rb
require 'action_view'

class Cat < ApplicationRecord
    include ActionView::Helpers::DateHelper
    #rails creates getter/setter to columns
    validates  :birth_date, :name, presence: true
    validates :sex, presence: true, inclusion: { in: ['M', 'F'] }
    CAT_COLORS = ['Brown', 'Black', 'White', 'Ginger', 'Grey', 'Cream', 'Cinnamon', 'Fawn' ]
    validates :color, presence: true, inclusion: { in: CAT_COLORS }
    validate :birth_date_cannot_be_future
    
    def birth_date_cannot_be_future
        errors.add(:birth_date, "cannot be in the future") unless birth_date < Date.today
    end

    def age
        time_ago_in_words(birth_date)
    end

end

99 Cats/cats_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

99 Cats/cats_app/app/controllers/cats_controller.rb
class CatsController < ApplicationController
    def index
        @cats = Cat.all
        render :index
    end

    def show
        @cat = Cat.find(params[:id])
        render :show
    end

    def create
        @cat = Cat.new(cat_params)
        if @cat.save
            redirect_to cat_url(@cat)
        else 
            render json: @cat.errors.full_messages, status: 422
        end
    end

    def update

    end

    def edit
        @cat_colors = Cat::CAT_COLORS
        @cat = Cat.find(params[:id])
        render :edit
    end

    def new
        @cat_colors = Cat::CAT_COLORS
        @cat = Cat.new
        render :new
    end

    private

    def cat_params
        params.require(:cat).permit(:birth_date, :name, :sex, :color)
    end
end

99 Cats/cats_app/app/helpers/application_helper.rb
module ApplicationHelper
end

99 Cats/cats_app/app/helpers/cats_helper.rb
module CatsHelper
end

99 Cats/cats_app/app/views/cats/_form.html.erb
<% if type == :new %>
    <% action_url = cats_url %>
    <% button_text = "Create cat" %>
<% else %>
    <% action_url = cat_url(cat) %>
    <% button_text = "Update cat" %>
<% end %>

<form action="<% action_url %>"  method= "POST">


    <% if type == :edit %>
        <input type="hidden" name="_method" value="PATCH">
    <% end %>


    <label> Name: 
        <input type = "text" name = "cat[name]" value = "<%= cat.name %>"  >
    </label>

    <br>
    
    <label> Birthday: 
        <input type = "date" name = "cat[birth_date]" value = "<%= cat.birth_date %>" >
    </label>
    <br>

    <label> Gender: 
        <select id="sex" name="cat[sex]" selected = "<%cat.sex%>">
            <option selected disabled> --Select a gender-- </option>
            <option <%= cat.sex == 'M' ? 'selected' : '' %> >M</option>
            <option <%= cat.sex == 'F' ? 'selected' : '' %> >F</option>
        </select>
    </label>

    <br>

    <label for="color">Color</label> 
        <select id ="color" name="cat[color]" >
        <option selected disabled> --Select a color-- </option>
        <% @cat_colors.each do |color| %>
            <option <%=cat.color == color ? 'selected' : ''%> ><%= color %></option>
        <% end %>>
        </select>
    <br>

    <input type="submit" value=<%=button_text%>>

</form>

        

    

99 Cats/cats_app/app/views/cats/edit.html.erb
<h1> Edit a cat </h1>

<%= render 'form', cat: @cat, type: :edit %>
        

    

99 Cats/cats_app/app/views/cats/index.html.erb
<h1> These are all the cats! </h1>
<ul>
    <% @cats.each do |cat| %>
        <li><%= cat.name %></li>
    <% end %>
</ul>

99 Cats/cats_app/app/views/cats/new.html.erb
<h1> Add a new cat </h1>
    
<%= render 'form', cat: @cat, type: :new %>

99 Cats/cats_app/app/views/cats/show.html.erb
<h1> This is <%= @cat.name%> (show) </h1>

<table>
    <thead>
        <tr>
            <th> <%= @cat.name%>
        </tr>
    </thead>

    <tbody>
        <tr>
            <td> Gender: </td>
            <td> <%= @cat.sex %></td>

        <tr>
        <tr>
            <td> Birthday: </td>
            <td> <%= @cat.birth_date %> </td>
        <tr>
        <tr>
            <td> Age:  </td>
            <td> <%= @cat.age  %></td>
        <tr>
        <tr>
            <td> Color: </td>
            <td> <%= @cat.color %> </td>

        <tr>
    </tbody>
</table>

99 Cats/cats_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CatsApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>